networks:
  laravel-net:
    name: laravel-net

services:
  # Laravel service
  laravel:
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    expose:
      - '8000'
    environment:
      - DATABASE_HOST=0.0.0.0
      - DATABASE_PORT=3306
      - DATABASE_NAME=nexus
      - DATABASE_USER=nexus
      - DATABASE_PASSWORD=nexus
    depends_on:
      - postgresql
    networks:
      - laravel-net

  # Vuejs service
  vuejs:
    build:
      context: ./front/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    expose:
      - '3000'
    depends_on:
      - laravel
    networks:
      - laravel-net

  # PostgreSQL service
  postgresql:
    container_name: postgresql
    build: 
      context: ./postgres/
      dockerfile: Dockerfile
    ports:
      - '5434:5432'
    expose:
      - '5432'
    networks:
      - laravel-net
    environment:
      - POSTGRESQL_DATABASE=nexus
      - POSTGRESQL_USER=nexus
      - POSTGRESQL_PASSWORD=nexus
    restart: always
    volumes:
      - db_data:/var/lib/pgsql/data

volumes:
  db_data: {}
