services:
  # Laravel service
  laravel:
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgresql
    networks:
      - laravel

  # Vuejs service
  vuejs:
    build:
      context: ./front/
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'
    depends_on:
      - laravel
    networks:
      - laravel

  # PostgreSQL service
  postgresql:
    container_name: postgresql
    build: 
      context: ./postgres/
      dockerfile: Dockerfile
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    expose:
      - '5432'
    networks:
      - laravel
    environment:
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
    restart: always
    volumes:
      - db_data:/var/lib/pgsql/data

volumes:
  db_data: {}
  app: {}


networks:
  laravel:
    driver: bridge
